#ifndef CLA_CLA_H_INCLUDED
#define CLA_CLA_H_INCLUDED
#include "cla/export.h"       // generated by CMake, defines CLA_EXPORT
#include <stdio.h>

// forward declaration of abstract data type `struct cla` holding
// information about the command line arguments
typedef struct cla Cla;
struct cla;

CLA_EXPORT void CLA_add_flag (struct cla * self, const char * name, const char * alias);
CLA_EXPORT void CLA_add_optional (struct cla * self, const char * name, const char * alias);
CLA_EXPORT void CLA_add_positionals (struct cla * self, int npositionals);
CLA_EXPORT void CLA_add_required (struct cla * self, const char * name, const char * alias);
CLA_EXPORT int CLA_count_flag (const struct cla * self, const char * name);
CLA_EXPORT struct cla * CLA_create (void);
CLA_EXPORT void CLA_destroy (struct cla ** self);
CLA_EXPORT const char * CLA_get_value_optional (const struct cla * self, const char * name);
CLA_EXPORT const char * CLA_get_value_positional (const struct cla * self, int ipos);
CLA_EXPORT const char * CLA_get_value_required (const struct cla * self, const char * name);
CLA_EXPORT bool CLA_has_flag (const struct cla * self, const char * name);
CLA_EXPORT bool CLA_has_optional (const struct cla * self, const char * name);
CLA_EXPORT void CLA_parse (struct cla * self, int argc, const char * argv[]);
CLA_EXPORT void CLA_parsed_as (const struct cla * self, FILE * stream);

#endif
