.TH cla 3
.SH NAME
cla \- command line argument handling
.SH LIBRARY
cla (\fIlibcla\fR, \fI\-lcla\fR)

.SH DESCRIPTION
Available API man pages:

.TS
l l.
\fBCLA_add_flag\fR	Register a flag argument
\fBCLA_add_optional\fR	Register an optional named argument
\fBCLA_add_positionals\fR	Register the number of positional arguments
\fBCLA_add_required\fR	Register a required named argument
\fBCLA_count_flag\fR	Count the usages of a flag
\fBCLA_create\fR	Allocate memory necessary for argument classification
\fBCLA_destroy\fR	Free the memory allocated by \fBcla_create\fR
\fBCLA_get_exename\fR	Get the name of the executable
\fBCLA_get_value_optional\fR	Get the value associated with an optional named argument
\fBCLA_get_value_positional\fR	Get the value associated with a positional argument
\fBCLA_get_value_required\fR	Get the value associated with a required named argument
\fBCLA_has_flag\fR	Assess whether the user-provided arguments include a given flag argument
\fBCLA_has_optional\fR	Assess whether the user-provided arguments include a given optional named argument
\fBCLA_help_requested\fR	Assess whether the user requested help
\fBCLA_parse\fR	Parse the user-provided arguments
\fBCLA_parsed_as\fR	Print how the user-provided arguments were understood by the program
.TE
