.TH CLA_add_required 3
.SH NAME
.PP
CLA_add_required \- Register a required argument
.SH LIBRARY
.PP
cla (\fIlibcla\fR, \fI\-lcla\fR)
.SH SYNOPSIS
.PP
.B #include \[dq]cla/cla.h\[dq]
.PP
\fBvoid CLA_add_required (struct cla * self, const char * name, const char * alias);
.SH DESCRIPTION
.PP
Register a required argument whose name is \fIname\fR and whose alias is \fIalias\fR. 
.PP
\fIname\fR should start with '--', be between 4 and 64 characters long (not including the
terminating null character), and consist only of alphanumeric characters [0-9a-zA-Z].
.PP
\fIalias\fR should start with '-', be 2 characters long (not including the terminating null
character), and consist only of alphanumeric characters [0-9a-zA-Z].
.PP
In addition, one of \fIname\fR and \fIalias\fR may be left
unspecified by assigning it a nullptr value.
.SH EXAMPLES
.PP
.EX
#include "cla/cla.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char * argv[]) {

    // allocate dynamic memory to store information about
    // what arguments to expect
    struct cla * cla = CLA_create();

    // define a few required arguments
    CLA_add_required(cla, "--nsamples", "-n");
    CLA_add_required(cla, "--freq", nullptr);
    CLA_add_required(cla, nullptr, "-f");

    // parse the command line arguments and store the result in `cla`
    CLA_parse(cla, argc, argv);

    // print the value of each positional argument
    fprintf(stdout,
           "--nsamples/-n=%s\\n",
           CLA_get_value_required(cla, "--nsamples"));

    fprintf(stdout,
           "--freq=%s\\n",
           CLA_get_value_required(cla, "--freq"));

    fprintf(stdout,
           "-f=%s\\n",
           CLA_get_value_required(cla, "-f"));

    // free memory resources
    CLA_destroy(&cla);

    // exit
    return EXIT_SUCCESS;
}
.EE
.PP
Here's some sample output of the above program:
.EX
.PP
$ ./example-required
ERROR: Required key '-n/--nsamples' not found, aborting.
.PP
$ ./example-required --nsamples
ERROR: '--nsamples' requires a value but none given, aborting.
.PP
$ ./example-required --nsamples 12
ERROR: Required key '--freq' not found, aborting.
.PP
$ ./example-required --nsamples 12 --freq 11000
ERROR: Required key '-f' not found, aborting.
.PP
$ ./example-required --nsamples 12 --freq 11000 -f file.wav
--nsamples/-n=12
--freq=11000
-f=file.wav
.PP
$ ./example-required --nsamples 12 --freq 11000 -f file.wav -n 23
ERROR: Found multiple usages of key '-n/--nsamples', aborting.
.EE
.SH SEE ALSO
.PP
\fBCLA\fR(3), \fBCLA_get_value_required\fR(3)
