.TH CLA_get_value_positional 3
.SH NAME
.PP
CLA_get_value_positional \- Get the value associated with a positional argument
.SH LIBRARY
.PP
cla library (\fIlibcla\fR, \fI\-lcla\fR)
.SH SYNOPSIS
.B #include \[dq]cla/cla.h\[dq]
.PP
\fBconst char * CLA_get_value_positional (const struct cla * \fIself\fR\fB, int \fIipos\fR\fB);
.SH DESCRIPTION
.PP
.B CLA_get_value_positional
gets the value associated with a registered positional command line argument at index \fIipos\fR,
using the information from \fIself\fR. Indexing is 0-based and starts at the first
positional argument.
.PP
.I self
can be constructed using
\fBCLA_create\fR.
.PP
Registering the number of positional arguments can be done with
\fBCLA_add_positionals\fR.
.SH RETURN VALUE
.PP
A pointer to the positional argument at index \fIipos\fR. Any subsequent parsing is left to the user.
.SH EXAMPLES
.PP
The code example below represents a program that expects exactly two positional arguments, which it
prints when the program is invoked. 
.IP
.EX
#include "cla/cla.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char * argv[]) {

    // allocate dynamic memory to store information about
    // what arguments to expect
    struct cla * cla = CLA_create();

    // specify that the program will have exactly 2
    // positional arguments
    CLA_add_positionals(cla, 2);

    // parse the arguments that the user provided
    CLA_parse(cla, argc, argv);

    // print the value of the first positional
    fprintf(stdout, "positional[0] = %s\\n",
            CLA_get_value_positional(cla, 0));

    // print the value of the second positional
    fprintf(stdout, "positional[1] = %s\\n",
            CLA_get_value_positional(cla, 1));

    // free memory resources
    CLA_destroy(&cla);

    // exit
    return EXIT_SUCCESS;
}
.EE
.PP
Here's some sample output of the above program:
.IP
.EX
$ ./example-positionals 
ERROR: Expected at least 2 positional arguments, aborting.
.EE
.IP
.EX
$ ./example-positionals "the first" "the second"
positional[0]=the first
positional[1]=the second
.EE
.SH SEE ALSO
.PP
\fBCLA\fR(3), \fBCLA_add_positionals\fR(3), \fBCLA_create\fR(3)
