.TH CLA_add_flag 3
.SH NAME
CLA_add_flag \- Register a flag argument
.SH LIBRARY
cla (\fIlibcla\fR, \fI\-lcla\fR)
.SH SYNOPSIS
.B #include \[dq]cla/cla.h\[dq]
.br
\fBvoid CLA_add_flag (struct cla * self, const char * name, const char * alias);
.SH DESCRIPTION
.B CLA_add_flag
TODO.

.SH SEE ALSO
\fBCLA\fR(3), \fBCLA_count_flag\fR(3), \fBCLA_has_flag\fR(3)
