.TH CLA_parsed_as 3
.SH NAME
.PP
CLA_parsed_as \- Print how the user-provided arguments were understood by the program
.SH LIBRARY
.PP
cla library (\fIlibcla\fR, \fI\-lcla\fR)
.SH SYNOPSIS
.PP
.B #include \[dq]cla/cla.h\[dq]
.PP
\fBvoid CLA_parsed_as (const struct cla * \fIself\fR\fB, FILE * \fIstream\fR\fB);
.SH DESCRIPTION
.PP
.B CLA_parsed_as
uses
.I stream
to print a table of command line arguments received by the program,
along with an indicator of how
.B CLA_parse
classified each argument provided by the user. Each argument is one of:
.IP
1. executable name
.IP
2. required named argument
.IP
3. optional named argument
.IP
4. flag argument
.IP
5. positional argument
.IP
6. value
.PP
.I self
can be constructed using
\fBCLA_create\fR.
.SH EXAMPLES
.PP
The code example below represents a program that expects exactly two (unnamed) positional arguments
and exactly one required named argument (\[dq]--aa\[dq]/\[dq]-a\[dq]); it additionally expects an
optional named argument (\[dq]--bb\[dq]/\[dq]-b\[dq]), and an (optional) flag
(\[dq]--cc\[dq]/\[dq]-c\[dq]). The program prints its interpretation of each argument that the user
provided during invocation.
.IP
.EX
#include "cla/cla.h"
#include <stdio.h>
#include <stdlib.h>

int main (int argc, const char * argv[]) {
    // create the command line arguments object
    struct cla * cla = CLA_create();

    // register a required named argument with a name and an alias
    CLA_add_required(cla, "--aa", "-a");

    // register an optional named argument with a name and an alias
    CLA_add_optional(cla, "--bb", "-b");

    // register a flag argument with a name and an alias
    CLA_add_flag(cla, "--cc", "-c");

    // specify that the program will have exactly 2 positional arguments
    CLA_add_positionals(cla, 2);

    // parse the arguments that the user provided
    CLA_parse(cla, argc, argv);

    // handle help requests
    if (CLA_help_requested(cla)) {
        fprintf(stdout, "Usage: example-parse REQUIREDS [OPTIONALS] [FLAGS] POS0 POS1\\n"
                        "\\n"
                        "  Requireds:\\n"
                        "    --aa, -a <VAL>     ... description ...\\n"
                        "\\n"
                        "  Optionals:\\n"
                        "    --bb, -b <VAL>     ... description ...\\n"
                        "\\n"
                        "  Flags:\\n"
                        "    --cc, -c           ... description ...\\n"
                        "\\n"
                        "  Positionals:\\n"
                        "    POS0               ... description ...\\n"
                        "    POS1               ... description ...\\n"
                        "\\n");
        exit(EXIT_SUCCESS);
    }

    // show how the program understood each of the user-provided arguments
    CLA_parsed_as(cla, stdout);

    // free memory resources
    CLA_destroy(&cla);

    // exit
    return EXIT_SUCCESS;
}
.EE
.PP
Let's see how that works in practice:
.IP
.EX
$ ./example-parse
ERROR 30: Expected at least 2 positional arguments, aborting.
.EE
.PP
OK, so add a value for the positional arguments:
.IP
.EX
$ ./example-parse pos0 pos1
ERROR 20: Required key '-a/--aa' not found, aborting.
.EE
.PP
Makes sense, our program above expects an argument named -a or --aa; let's add it then:
.IP
.EX
$ ./example-parse -a pos0 pos1
ERROR 31: '-a' requires a value but none given or not all positionals have been defined, aborting.
.EE
.PP
Ah yes, -a is a key-value pair so it needs a value:
.IP
.EX
$ ./example-parse -a value-of-a pos0 pos1
User-provided arguments were parsed as follows:
exename    ./example-parse
required   -a
value      value-of-a
positional pos0
positional pos1
.EE
.PP
It works! But we haven't tried with the optional arguments yet. Let's see what the help says:
.IP
.EX
$ ./example-parse --help
Usage: example-parse REQUIREDS [OPTIONALS] [FLAGS] POS0 POS1

  Requireds:
    --aa, -a <VAL>     ... description ...

  Optionals:
    --bb, -b <VAL>     ... description ...

  Flags:
    --cc, -c           ... description ...

  Positionals:
    POS0               ... description ...
    POS1               ... description ...

.EE
.PP
With optional named argument --bb/-b and flag --cc/-c:
.IP
.EX
$ ./example-parse -a value-of-a -b value-of-b -c --cc pos0 pos1
User-provided arguments were parsed as follows:
exename    ./example-parse
required   -a
value      value-of-a
optional   -b
value      value-of-b
flag       -c
flag       --cc
positional pos0
positional pos1
.EE
.PP
Note that flags may be repeated, but required and optional named arguments can only appear once.
.EE
.SH SEE ALSO
.PP
\fBCLA\fR(3), \fBCLA_create\fR(3), \fBCLA_parse\fR(3)
