.TH CLA_add_optional 3
.SH NAME
CLA_add_optional \- Register an optional argument
.SH LIBRARY
cla (\fIlibcla\fR, \fI\-lcla\fR)
.SH SYNOPSIS
.B #include \[dq]cla/cla.h\[dq]
.br
\fBvoid CLA_add_optional (struct cla * self, const char * name, const char * alias);
.SH DESCRIPTION
Register an optional argument whose name is \fIname\fR and whose alias is \fIalias\fR. \fIname\fR
should start with '--', be between 4 and 64 characters long (not including the terminating null
character), and consist only of alphanumeric characters [0-9a-zA-Z]. \fIalias\fR should start
with '-', be 2 characters long (not including the terminating null character), and consist only of
alphanumeric characters [0-9a-zA-Z]. In addition, one of \fIname\fR and \fIalias\fR may be left
unspecified by assigning it a nullptr value. Optional arguments may not be used more than one time.
.SH EXAMPLES
.PP
.EX
#include "cla/cla.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char * argv[]) {

    // allocate dynamic memory to store information about what arguments to expect
    struct cla * cla = CLA_create();

    // define a few flags
    CLA_add_optional(cla, "--directory", "-d");
    CLA_add_optional(cla, "--author", nullptr);
    CLA_add_optional(cla, nullptr, "-l");

    // parse the command line arguments and store the result in `cla`
    CLA_parse(cla, argc, argv);

    // print the value of each optional argument, if it was used at all
    if (CLA_has_optional(cla, "--directory")) {
        fprintf(stdout,
                "--directory/--d=%s\\n",
                CLA_get_value_optional(cla, "--directory"));
    }

    if (CLA_has_optional(cla, "-l")) {
        fprintf(stdout,
                "-l=%s\\n",
                CLA_get_value_optional(cla, "-l"));
    }

    if (CLA_has_optional(cla, "--author")) {
        fprintf(stdout,
                "--author=%s\\n",
                CLA_get_value_optional(cla, "--author"));
    }

    // free memory resources
    CLA_destroy(&cla);
    return EXIT_SUCCESS;
}
.EE
.PP
Here's some sample output of the above program:
.PP
.EX
 $ ./dist/bin/example-cla-add-optional 
$ ./dist/bin/example-cla-add-optional --directory
ERROR: '--directory' requires a value but none given, aborting.
$ ./dist/bin/example-cla-add-optional --directory the_directory
--directory/--d=the_directory
$ ./dist/bin/example-cla-add-optional --author the_author
--author=the_author
$ ./dist/bin/example-cla-add-optional -l the_length
-l=the_length
$ ./dist/bin/example-cla-add-optional --directory the_directory --author the_author -l
ERROR: '-l' requires a value but none given, aborting.
$ ./dist/bin/example-cla-add-optional --directory the_directory --author the_author -l the_length
--directory/--d=the_directory
-l=the_length
--author=the_author
.EE
.PP
.SH SEE ALSO
\fBCLA\fR(3), \fBCLA_get_value_optional\fR(3), \fBCLA_has_optional\fR(3)
