.TH CLA_add_flag 3
.SH NAME
.PP
CLA_add_flag \- Register a flag argument
.SH LIBRARY
.PP
cla (\fIlibcla\fR, \fI\-lcla\fR)
.SH SYNOPSIS
.PP
.B #include \[dq]cla/cla.h\[dq]
.PP
\fBvoid CLA_add_flag (struct cla * self, const char * name, const char * alias);
.SH DESCRIPTION
.PP
Register a flag argument whose name is \fIname\fR and whose alias is \fIalias\fR.
.PP
\fIname\fR should start with '--', be between 4 and 64 characters long (not including the
terminating null character), and consist only of alphanumeric characters [0-9a-zA-Z].
.PP
\fIalias\fR should start with '-', be 2 characters long (not including the terminating null
character), and consist only of alphanumeric characters [0-9a-zA-Z].
.PP
In addition, one of \fIname\fR and \fIalias\fR may be left unspecified by
assigning it a \fBnullptr\fR value.
.SH EXAMPLES
.PP
The code example below represents a program that expects three flags: one that can be referenced
through its name \[dq]--directory\[dq] and its alias \[dq]-d\[dq]; one that can be referenced only
through its name \[dq]--author\[dq]; and one that can be referenced only through its alias
\[dq]-l\[dq]. It prints the number of times each of its flags was actually used when invoking the
program, provided the flag was used at all.
.IP
.EX
#include "cla/cla.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, const char * argv[]) {

    // allocate dynamic memory to store information about
    // what arguments to expect
    struct cla * cla = CLA_create();

    // define a few flags
    CLA_add_flag(cla, "--directory", "-d");
    CLA_add_flag(cla, "--author", nullptr);
    CLA_add_flag(cla, nullptr, "-l");

    // parse the command line arguments and store the result in `cla`
    CLA_parse(cla, argc, argv);

    // print how many times each flag was used, if it was used at all
    if (CLA_has_flag(cla, "--directory")) {
        fprintf(stdout,
                "--directory/--d was used %d times\\n",
                CLA_count_flag(cla, "--directory"));
    }

    if (CLA_has_flag(cla, "-l")) {
        fprintf(stdout,
                "-l was used %d times\\n",
                CLA_count_flag(cla, "-l"));
    }

    if (CLA_has_flag(cla, "--author")) {
        fprintf(stdout,
                "--author was used %d times\\n",
                CLA_count_flag(cla, "--author"));
    }

    // free memory resources
    CLA_destroy(&cla);

    // exit
    return EXIT_SUCCESS;
}
.EE
.PP
Here's some sample output of the above program:
.IP
.EX
$ ./example-flag
.EE
.IP
.EX
$ ./example-flag -l -l --author -d --directory
--directory/--d was used 2 times
-l was used 2 times
--author was used 1 times
.EE
.IP
.EX
$ ./example-flag --author
--author was used 1 times
.EE
.SH SEE ALSO
.PP
\fBCLA\fR(3), \fBCLA_count_flag\fR(3), \fBCLA_has_flag\fR(3)
