.TH CLA_add_optional 3
.SH NAME
CLA_add_optional \- Register an optional argument
.SH LIBRARY
cla (\fIlibcla\fR, \fI\-lcla\fR)
.SH SYNOPSIS
.B #include \[dq]cla/cla.h\[dq]
.br
\fBvoid CLA_add_optional (struct cla * self, const char * name, const char * alias);
.SH DESCRIPTION
.B CLA_add_optional
TODO.

.SH SEE ALSO
\fBCLA\fR(3), \fBCLA_has_optional\fR(3), \fBCLA_get_value_optional\fR(3)
