.TH CLA_create 3
.SH NAME
CLA_create \- Allocate memory necessary for argument classification
.SH LIBRARY
cla (\fIlibcla\fR, \fI\-lcla\fR)
.SH SYNOPSIS
.B #include \[dq]cla/cla.h\[dq]
.br
\fBstruct cla * CLA_create (void);
.SH DESCRIPTION
.B CLA_create
allocates memory necessary for parsing command line arguments into flags, required arguments,
optional arguments, positional arguments, and values.

.SH RETURN VALUE
A pointer to the abstract object required for command line argument parsing.
The user is responsible for freeing the memory allocated by \fBCLA_create\fR using
\fBCLA_destroy\fR.
.SH SEE ALSO
\fBCLA\fR(3), \fBCLA_destroy\fR(3)
